# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_sexp_mat_to_vcl_sp_mat <- function(ptrA, type_flag, ctx_id) {
    .Call(`_gpuRsparse_cpp_sexp_mat_to_vcl_sp_mat`, ptrA, type_flag, ctx_id)
}

sp_vcl_to_sexp <- function(ptrA, type_flag, ctx_id) {
    .Call(`_gpuRsparse_sp_vcl_to_sexp`, ptrA, type_flag, ctx_id)
}

run_tutorial <- function() {
    invisible(.Call(`_gpuRsparse_run_tutorial`))
}

